name: Setup Build Environment

inputs:
  DOCKER_VERSION:
    description: 'Docker version'
    required: false

runs:
  using: "composite"
  steps:
  - name: Checkout code
    uses: actions/checkout@v2
    
  - name: setup promu
    run: make promu 
    shell: bash
  
  - name: Add promu to PATH
    run: |
      export GOPATH=/home/runner/go
      echo /home/runner/go/bin >> $GITHUB_PATH
    shell: bash

  - name: Setup Docker
    uses: docker/setup-buildx-action@v1
    with:
      version: ${{ env.DOCKER_VERSION }}
      
  - name: Display Docker version
    run: docker version
    shell: bash
    
  - name: Run Docker command
    run: docker run --privileged linuxkit/binfmt:v0.8
    shell: bash
    
  - name: Attach Workspace
    uses: actions/upload-artifact@v2
    with:
      name: workspace
      path: .