name: Build and Publish Images


inputs:
  DOCKERFILE_PATH:
    description: 'Path to Dockerfile'
    required: false
    default: ''
  DOCKER_IMAGE_NAME:
    description: 'Name of Docker image'
    required: true
    default: 'node_exporter'
  DOCKERBUILD_CONTEXT:
    description: 'Path to Docker build context'
    required: false
    default: ''
  REGISTRY:
    description: 'Docker registry'
    required: true
  ORGANIZATION:
    description: 'Docker organization'
    required: true

runs:
  using: "composite"  
  steps:
  - name: setup promu
    run: make promu 
    shell: bash
  
  - name: Add promu to PATH
    run: |
      export GOPATH=/home/runner/go
      echo /home/runner/go/bin >> $GITHUB_PATH
    shell: bash

  - name: Setup Docker
    uses: docker/setup-buildx-action@v1
    with:
      version: ${{ env.DOCKER_VERSION }}
      
  - name: Display Docker version
    run: docker version
    shell: bash
    
  - name: Run Docker command
    run: docker run --privileged linuxkit/binfmt:v0.8
    shell: bash
    
  - name: Attach Workspace
    uses: actions/upload-artifact@v2
    with:
      name: workspace
      path: .
      
  - name: Set Environment Variables
    if: ${{ inputs.DOCKERFILE_PATH != '' }}
    run: |
      echo "DOCKERFILE_PATH=${{ inputs.DOCKERFILE_PATH }}" >> $GITHUB_ENV
    shell: bash

  - name: Set Environment Variables
    if: ${{ inputs.DOCKER_IMAGE_NAME != '' }}
    run: |
      echo "DOCKER_IMAGE_NAME=${{ inputs.DOCKER_IMAGE_NAME }}" >> $GITHUB_ENV
    shell: bash
    
  - name: Set Environment Variables
    if: ${{ inputs.DOCKERBUILD_CONTEXT != '' }}
    run: |
      echo "DOCKERBUILD_CONTEXT=${{ env.DOCKERBUILD_CONTEXT }}" >> $GITHUB_ENV
    shell: bash

  - name: Setup Docker
    uses: docker/setup-buildx-action@v1

  - name: Build Docker Image
    run: make docker DOCKER_REPO=${{ inputs.REGISTRY }}/${{ inputs.ORGANIZATION }}
    shell: bash
    
  - name: List Docker Images
    run: docker images
    shell: bash

  - name: Docker Login
    run: echo ${{ env.DOCKER_PASSWORD }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin ${{ env.REGISTRY }}
    shell: bash

  - name: Publish Docker Image
    run: make docker-publish DOCKER_REPO=${{ inputs.REGISTRY }}/${{ inputs.ORGANIZATION }}
    shell: bash

  - name: Manifest Docker Image
    run: make docker-manifest DOCKER_REPO=${{ inputs.REGISTRY }}/${{ inputs.ORGANIZATION }}
    shell: bash